### ISSUE TITLE
Acknowledge LAVIS

### ISSUE THREAD

**Issue by dxli94** [DCDmllm/Cheetah#5]
Hi @YYJMJC,

Congrats on the work!

The Cheetah implementation seems to overlap largely with LAVIS. I wonder if you would mind adding LAVIS library to acknowledgement section, and also referencing it in the paper.

Thanks.

**Comment by WestbrookGE** [comment]
I apologize for the oversight in omitting the acknowledgement of the LAVIS Library. It's undeniable that our work would not have reached fruition without LAVIS. We have updated our acknowledgment on our GitHub pages and will ensure the reference is included in the upcoming version of our paper.

**Comment by dxli94** [comment]
Thanks!
