### ISSUE TITLE
How can I change the LLM with other and finetune it on my own dataset?

### ISSUE THREAD

**Issue by joaopedrosdmm** [DCDmllm/Cheetah#9]
I would like to remove the Vicuma LLM and change it with another LLM how can I achieve this with Cheetah?

**Comment by WestbrookGE** [comment]
Thank you for reaching out. As of now, Cheetah is specifically designed to work with Vicuna-7B and LLaMA2-7B as LLMs. Unfortunately, we don't support changing the LLM at the moment.

We appreciate your interest and suggest keeping an eye on our repository for any future updates or enhancements.
